### PR TITLE
#167190389 Travis and CodeCilmate

### PR DESCRIPTION
**Pull request by cvjude**
#### What does this PR do?
- Sets up unit testing for the App

#### How can this be manually tested?
- Clone the repo
- Run the command below in your terminal to install all dependencies
```
npm install
``` 
- Run the command below to test
```
npm test
```

#### Any background context you want to provide?
none

#### What are the relevant Pivotal Tracker stories? 
- [#167190389](https://www.pivotaltracker.com/story/show/167190389)

### CODE REVIEW

**Review by Hadeneekeh — APPROVED** [review]
LGTM

**Review by chiboycalix — APPROVED** [review]
LGTM

**Review by obayomi96 — APPROVED** [review]
Great Job. LGTM

**Review by encodedBicoding — APPROVED** [review]
LGTM

**Review by chuxmykel — COMMENTED** [review]
Great job guys.

**Review by topseySuave — APPROVED** [review]

**Pull request merged**
