### PR TITLE
 #167190388 Setup end-to-end-testing

### PR DESCRIPTION
**Pull request by chiboycalix**
#### Description of Task to be completed?
- Install nightwatch as a dependency
- Install chromedriver dependency
- Create nightwatch config file
- Write tests
#### What are the relevant pivotal tracker stories?
[#167190388](https://www.pivotaltracker.com/story/show/167190388)
#### Screenshots (if appropriate)

Screenshot 2019-08-28 at 9 58 35 AM

Screenshot 2019-08-28 at 9 58 46 AM

### CODE REVIEW

**Review by Lundii — APPROVED** [review]
LGTM

**Review by Hadeneekeh — APPROVED** [review]
LGTM! Great work @chiboycalix

**Review by encodedBicoding — APPROVED** [review]
LGTM!

**Review by chuxmykel — APPROVED** [review]
Great Job @chiboycalix. Works like a charm. However, the `initialTest.js` file exists twice. one in the `src/tests/initialTest.js` directory and one in `src/e2e/initialTest.js` directory. Kindly delete the unnecessary one. Great job once again.

**Review by obayomi96 — APPROVED** [review]
Good job @chiboycalix .

**Pull request merged**
