### PR TITLE
#168466772 refactored search functionality

### PR DESCRIPTION
**Pull request by Lundii**
#### Description of Task to be completed?
Refactored the search functionality task
#### How should this be manually tested?
- created folders to group related files
- improved on design
- Increased the number of articles per page from 20 - 30
- Made the filters static
#### Any background context you want to provide?
-N/A
#### What are the relevant pivotal tracker stories?
[#168466772](https://www.pivotaltracker.com/story/show/168466772)
#### Screenshots (if appropriate)
N/A
#### Questions:
N/A

### CODE REVIEW

**Comment by Hadeneekeh** [comment]
Hello @Lundii, please provide the necessary details on your pull request description for better communication of what this PR is all about.

**Comment by Lundii** [comment]
> Hello @Lundii, please provide the necessary details on your pull request description for better communication of what this PR is all about.

Yes, I will do that. The PR is not yet ready for review. Let me add a label to it.

**Comment by Lundii** [comment]
> > Hello @Lundii, please provide the necessary details on your pull request description for better communication of what this PR is all about.
> 
> Yes, I will do that. The PR is not yet ready for review. Let me add a label to it.

Done

**Review by Hadeneekeh — APPROVED** [review]
Nice work @Lundii 

LGTM!!!

**Review by cvjude — APPROVED** [review]
LGTM

**Pull request merged**
