### PR TITLE
#167190400 comment functionality on articles

### PR DESCRIPTION
**Pull request by obayomi96**
#### What does this PR do?
Implements comment functionality on articles

#### Description of Task to be completed?
- Users can view all comments an article has
- Users can add a comment to the list of existing comments

#### How should this be manually tested?
- View a single article
- Click on the comment icon and ensure you are authenticated
- When redirected to the comment page you will view all comments and can add a new comment
#### What are the relevant pivotal tracker stories?
#167190400

### CODE REVIEW

**Review by chuxmykel — APPROVED** [review]
LGTM

**Review by chiboycalix — APPROVED** [review]
LGTM

**Review by encodedBicoding — APPROVED** [review]
LGTM. Weldone Martins

**Review by Hadeneekeh — APPROVED** [review]
LGTM!!

**Review by Lundii — APPROVED** [review]
LGTM

**Review by cvjude — APPROVED** [review]
LGTM

**Pull request merged**
