### PR TITLE
#168383397 Fix styling on the Edit Profile page

### PR DESCRIPTION
**Pull request by chiboycalix**
#### What are the relevant pivotal tracker stories?
[#168383397](https://www.pivotaltracker.com/story/show/168383397)

### CODE REVIEW

**Review by Hadeneekeh — APPROVED** [review]
LGTM

**Review by obayomi96 — APPROVED** [review]
Thanks for revamping the inputs on the forms back to their initial look. Good job. LGTM

**Review by encodedBicoding — APPROVED** [review]
Nice work. LVGTM

**Review by Lundii — APPROVED** [review]
LGTM

**Pull request merged**
