### PR TITLE
#168380301 Fixes .env variables on production

### PR DESCRIPTION
**Pull request by encodedBicoding**
#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
[#168380301](https://www.pivotaltracker.com/story/show/168380301)

#### Screenshots (if appropriate)
N/A

#### Questions:
N/A

### CODE REVIEW

**Review by Hadeneekeh — APPROVED** [review]
LGTM!

**Review by chiboycalix — APPROVED** [review]
LGTM

**Review by obayomi96 — APPROVED** [review]
LGTM

**Review by Lundii — APPROVED** [review]
LGTM

**Review by chuxmykel — APPROVED** [review]
Nice. Works well. Looks good to me.

**Review by topseySuave — APPROVED** [review]

**Pull request merged**
