### PR TITLE
#167190402 Implements likes and dislikes on Articles

### PR DESCRIPTION
**Pull request by encodedBicoding**
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
[#167190402](https://www.pivotaltracker.com/story/show/167190402)
#### Screenshots (if appropriate)
Screenshot 2019-09-11 at 1 21 37 PM

#### Questions:
N/A

### CODE REVIEW

**Review by chuxmykel — APPROVED** [review]
LGTM

**Review by obayomi96 — APPROVED** [review]
Great job. LGTM

**Review by Hadeneekeh — APPROVED** [review]
LGTM

**Review by cvjude — COMMENTED** [review]
LGTM

**Pull request merged**
