### PR TITLE
#168374435 Implement password reset feedback

### PR DESCRIPTION
**Pull request by Hadeneekeh**
#### What does this PR do?
Has the implemented feedback on the password reset functionality

#### Description of Task to be completed?
- Changed the button label
- Removed toaster
-Display alert in modal

#### How should this be manually tested?
- Clone the repo
- Run `npm install`

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
[#168374435](https://www.pivotaltracker.com/n/projects/2364267/stories/168374435)

#### Screenshots (if appropriate)
N/A

#### Questions:
N/A

### CODE REVIEW

**Review by chiboycalix — APPROVED** [review]
LGTM

**Review by obayomi96 — APPROVED** [review]
Good job working on the feedback, I think your tests should give valid info once we integrate coveralls for code coverage

**Review by cvjude — COMMENTED** [review]
LGTM

**Review by cvjude — COMMENTED** [review]
LGTM

**Review by Lundii — APPROVED** [review]
LGTM

**Pull request merged**
